version: '3.2'

services:
  chrome:
    image: selenium/chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      HUB_HOST: selenium-hub
      MAX_INSTANCES: 5
      MAX_SESSIONS: 5
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
      - "5900:5900"
    links:
      - selenium-hub:hub
    networks:
      - test_network

  firefox:
    image: selenium/firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      HUB_HOST: selenium-hub
      MAX_INSTANCES: 5
      MAX_SESSIONS: 5
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
      - "5901:5900"
    links:
      - selenium-hub:hub
    networks:
      - test_network

  edge:
    image: selenium/edge
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      HUB_HOST: selenium-hub
      MAX_INSTANCES: 5
      MAX_SESSIONS: 5
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
    ports:
      - "5902:5900"
    links:
      - selenium-hub:hub
    networks:
      - apollo-ui-test

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    environment:
      HOST: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - test_network

  test:
    image: node:latest
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    links:
      - selenium-hub:hub
    environment:
      TEST_RAIL: ${TEST_RAIL}
    command: >
      bash -c "npm install
      && npm run webdriver-clean
      && npm run webdriver-update
      && npm run precondition
      && node run.js"
    networks:
      - test_network

networks:
  test_network:
